# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0fdbe89b6e73ed9e69d000d468a5c3697edf7b222d2cb44c312f6725517c6f34a587cce9e93cf42a6d32900897a000a4b2e13439be6f141e03b2f2d30b642e22

test:
  secret_key_base: 6d352694ac81cfe77174cc0b082882d909ea7152759fcebafbabe82e6a7356f6d4f8dc95acbefec8b3588e85a85cdd8c8198b76b4b068d7cbd5b2e0a3b52aae3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
